### ISSUE TITLE
Add a free license

### ISSUE THREAD

**Issue by pizzamaker** [Zeipt/Mycely#1]
This repo seems to be lacking a free license. I suggest AGPLv3 or later :)

**Comment by Zeipt** [comment]
Yes, @pizzamaker , and I really will need help with selecting the **proper one, which must be max free, but not violent for any used components**. I shall gather them and their licenses later and post list here. Hope you help me with selecting :)

**Comment by pizzamaker** [comment]
What do you mean by violent in this context?

**Comment by Zeipt** [comment]
I afraid that if I license Mycely under terms of MIT, for example, it could violate some used components licenses.

**Comment by Zeipt** [comment]
### ***Dev tools:***
Android SDK:			http://developer.android.com/sdk/terms.html
NodeJS:				https://raw.githubusercontent.com/nodejs/node/master/LICENSE
JXCore:				https://github.com/jxcore/jxcore/blob/master/JXCORE_LICENSE
Apache Cordova:			***Apache License, Version 2.0.***

### ***Cordova's plugins:***

com.borismus.webintent,
cordova-open,
cordova-plugin-x-socialsharing,
nl.madebymark.share,
phonegap-plugin-barcodescanner: 		***MIT***

cordova-plugin-console,
cordova-plugin-device,
cordova-plugin-dialogs,
cordova-plugin-file,
cordova-plugin-file-transfer,
cordova-plugin-network-information,
cordova-plugin-whitelist,
cordova-plugin-legacy-whitelist,
cordova-plugin-media,
org.apache.cordova.home,
cordova-plugin-crosswalk-webview,
de.appplant.cordova.plugin.badge:		***Apache License, Version 2.0.***

cordova-plugin-background-app:	Copyright (c) 2014 The Chromium Authors. All rights reserved.
				Redistribution and use in source and binary forms, with or without
				modification, are permitted provided that the following conditions are
				met:

				   * Redistributions of source code must retain the above copyright
				notice, this list of conditions and the following disclaimer.
				   * Redistributions in binary form must reproduce the above
				copyright notice, this list of conditions and the following disclaimer
				in the documentation and/or other materials provided with the
				distribution.
				   * Neither the name of Google Inc. nor the names of its
				contributors may be used to endorse or promote products derived from
				this software without specific prior written permission.

				THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
				"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
				LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
				A PARTICULAR PURPOSE ARE DBSDLAIMED. IN NO EVENT SHALL THE COPYRIGHT
				OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
				SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
				LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
				DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
				THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
				(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
				OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

io.jxcore.node:			Copyright (c) 2015, Nubisa Inc. and JXcore Contributors

				Permission to use, copy, modify, and/or distribute this software for any
				purpose with or without fee is hereby granted, provided that the above
				copyright notice and this permission notice appear in all copies.

				THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
				WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
				MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
				ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
				WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
				ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
				OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

				---

				 Reachability

				 Disclaimer: IMPORTANT:  This Apple software is supplied to you by Apple
				 Inc. ("Apple") in consideration of your agreement to the following
				 terms, and your use, installation, modification or redistribution of
				 this Apple software constitutes acceptance of these terms.  If you do
				 not agree with these terms, please do not use, install, modify or
				 redistribute this Apple software.

				 In consideration of your agreement to abide by the following terms, and
				 subject to these terms, Apple grants you a personal, non-exclusive
				 license, under Apple's copyrights in this original Apple software (the
				 "Apple Software"), to use, reproduce, modify and redistribute the Apple
				 Software, with or without modifications, in source and/or binary forms;
				 provided that if you redistribute the Apple Software in its entirety and
				 without modifications, you must retain this notice and the following
				 text and disclaimers in all such redistributions of the Apple Software.
				 Neither the name, trademarks, service marks or logos of Apple Inc. may
				 be used to endorse or promote products derived from the Apple Software
				 without specific prior written permission from Apple.  Except as
				 expressly stated in this notice, no other rights or licenses, express or
				 implied, are granted by Apple herein, including but not limited to any
				 patent rights that may be infringed by your derivative works or by other
				 works in which the Apple Software may be incorporated.

				 The Apple Software is provided by Apple on an "AS IS" basis.  APPLE
				 MAKES NO WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION
				 THE IMPLIED WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY AND FITNESS
				 FOR A PARTICULAR PURPOSE, REGARDING THE APPLE SOFTWARE OR ITS USE AND
				 OPERATION ALONE OR IN COMBINATION WITH YOUR PRODUCTS.

				 IN NO EVENT SHALL APPLE BE LIABLE FOR ANY SPECIAL, INDIRECT, INCIDENTAL
				 OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
				 SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
				 INTERRUPTION) ARISING IN ANY WAY OUT OF THE USE, REPRODUCTION,
				 MODIFICATION AND/OR DISTRIBUTION OF THE APPLE SOFTWARE, HOWEVER CAUSED
				 AND WHETHER UNDER THEORY OF CONTRACT, TORT (INCLUDING NEGLIGENCE),
				 STRICT LIABILITY OR OTHERWISE, EVEN IF APPLE HAS BEEN ADVISED OF THE
				 POSSIBILITY OF SUCH DAMAGE.

				 Copyright (C) 2014 Apple Inc. All Rights Reserved.


### ***JS, others:***

Bootstrap,
RTCMultiConnection,
JQuery,
JQuery-mobile,
Vue.js,
qrcode.js:			***MIT***

Jasny-Bootstrap:		***Apache License, Version 2.0.***

Genericons:			***GNU GENERAL PUBLIC LICENSE Version 2, June 1991***

Node-forge:			***BSD license***

PT Sans Narrow:			***SIL Open Font License, 1.1***

Multiselect:			***DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE***


### ***And "root" node-modules:***

Telehash,
NeDB,
rawgithub,
Socket.IO:			***MIT***

Node-forge:			***BSD license*** 

rimraf:				***The ISC License***


So, what is the most free license I can safely use for project?

**Comment by fallerOfFalls** [comment]
Most of these licenses are very permissive, and _can_ be sublicensed with strong copyleft (i.e. GPL or AGPL) so no problems there. Apache, MIT and BSD are mentioned explicitly in [this helpful slide](http://www.dwheeler.com/essays/floss-license-slide-image.png).

[SIL Open Font License](https://opensource.org/licenses/OFL-1.1) says "The fonts and derivatives,
however, cannot be released under any other type of license." so it would have to be a third party non-code asset? since it can't be relicensed as GPL/AGPL like everything else. Or just use some other fonts that are available under a GPL compatible license.

The ISC License is compatible according to [wikipedia](https://en.wikipedia.org/wiki/ISC_license) so no problems there.

Did I miss anything? Oh, the "do what the fuck you want" license is obviously GPL compatible.

So, I'd suggest finding new fonts, and then licensing everything under AGPL.

**Comment by pizzamaker** [comment]
According to the FSF, all of these are compatible with the AGPL, so you're good to go: https://www.gnu.org/licenses/license-list.en.html

**Comment by fallerOfFalls** [comment]
@pizzamaker Unless I'm missing something, the SIL Open Font License is colour coded as _incompatible_ with GPL (and therefore also AGPL). The colour code classifications are near the top of the page (it took me a while to find them).

Also, thanks for making me examine that page more closely. Now I understand the colour code classifications, it's a much better resource than anything else I'd been using.

**Comment by pizzamaker** [comment]
> The Open Font License (including its original release, version 1.0) is a free copyleft license for fonts. Its only unusual requirement is that when selling the font, you must redistribute it bundled with some software, rather than alone. Since a simple Hello World program will satisfy the requirement, it is harmless. Neither we nor SIL recommend the use of this license for anything other than fonts.

**Comment by fallerOfFalls** [comment]
That doesn't mean it's compatible with GPL.

**Comment by pizzamaker** [comment]
Derp, you're right! Sorry.

**Comment by fallerOfFalls** [comment]
:)

Yeah it's not immediately clear is it. And it's weird that licences can be approved by the fsf as free software, while not being compatible with GPL.

**Comment by Zeipt** [comment]
@pizzamaker , @fallerOfFalls , so, as I understand, this font (light condensed) http://www.fontsquirrel.com/fonts/roboto?q[term]=Roboto&q[search_check]=Y is compatible with GPL/AGPL, right?

**Comment by fallerOfFalls** [comment]
According to that page, yes, roboto light condensed has an Apache 2 licence which can be relicensed as GPL/AGPL.
